# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\user\PycharmProject\SMRPprjct\ui\from_designer\Admin_Film_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Admin_Film_list(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(604, 396)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("логотип_приложения.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.search_lineEdit = QtWidgets.QLineEdit(Form)
        self.search_lineEdit.setObjectName("search_lineEdit")
        self.gridLayout.addWidget(self.search_lineEdit, 0, 1, 1, 1)
        self.category_comboBox = QtWidgets.QComboBox(Form)
        self.category_comboBox.setObjectName("category_comboBox")
        self.gridLayout.addWidget(self.category_comboBox, 0, 2, 1, 1)
        self.gosearch_pushButton = QtWidgets.QPushButton(Form)
        self.gosearch_pushButton.setObjectName("gosearch_pushButton")
        self.gridLayout.addWidget(self.gosearch_pushButton, 0, 3, 1, 1)
        self.Film_tableWidget = QtWidgets.QTableWidget(Form)
        self.Film_tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.Film_tableWidget.setDragEnabled(False)
        self.Film_tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.Film_tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.Film_tableWidget.setObjectName("Film_tableWidget")
        self.Film_tableWidget.setColumnCount(5)
        self.Film_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Film_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Film_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Film_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Film_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Film_tableWidget.setHorizontalHeaderItem(4, item)
        self.gridLayout.addWidget(self.Film_tableWidget, 1, 0, 1, 4)
        self.backto_choose_pushButton = QtWidgets.QPushButton(Form)
        self.backto_choose_pushButton.setObjectName("backto_choose_pushButton")
        self.gridLayout.addWidget(self.backto_choose_pushButton, 2, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 2, 3, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Film_list", "KinoSearch"))
        self.label.setText(_translate("Form", "Поиск:"))
        self.gosearch_pushButton.setText(_translate("Form", "Найти"))
        item = self.Film_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ID"))
        item = self.Film_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Название:"))
        item = self.Film_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Жанр:"))
        item = self.Film_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Время:"))
        item = self.Film_tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Год выпуска:"))
        self.backto_choose_pushButton.setText(_translate("Form", "Назад к выбору"))
        self.pushButton.setText(_translate("Form", "Добавить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
