# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\user\PycharmProject\SMRPprjct\ui\from_designer\Admin_Actor_Info.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Admin_Actor_Info(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 164)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("логотип_приложения.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.actors_name_lineEdit = QtWidgets.QLineEdit(Form)
        self.actors_name_lineEdit.setObjectName("actors_name_lineEdit")
        self.gridLayout.addWidget(self.actors_name_lineEdit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.actors_bdate_lineEdit = QtWidgets.QLineEdit(Form)
        self.actors_bdate_lineEdit.setObjectName("actors_bdate_lineEdit")
        self.gridLayout.addWidget(self.actors_bdate_lineEdit, 1, 1, 1, 1)
        self.Just_Do_It_pushButton = QtWidgets.QPushButton(Form)
        self.Just_Do_It_pushButton.setObjectName("Just_Do_It_pushButton")
        self.gridLayout.addWidget(self.Just_Do_It_pushButton, 2, 2, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Film_list", "KinoSearch"))
        self.label.setText(_translate("Form", "Имя:"))
        self.label_2.setText(_translate("Form", "Дата:"))
        self.Just_Do_It_pushButton.setText(_translate("Form", "Применить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
