# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\user\PycharmProject\SMRPprjct\ui\from_designer\Film_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Film_info_window(object):
    def setupUi(self, Film_info_window):
        Film_info_window.setObjectName("Film_info_window")
        Film_info_window.resize(834, 513)
        self.gridLayout = QtWidgets.QGridLayout(Film_info_window)
        self.gridLayout.setObjectName("gridLayout")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("логотип_приложения.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Film_info_window.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(Film_info_window)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Film_info_window)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.goto_actors_pushButton = QtWidgets.QPushButton(Film_info_window)
        self.goto_actors_pushButton.setObjectName("goto_actors_pushButton")
        self.gridLayout.addWidget(self.goto_actors_pushButton, 8, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(Film_info_window)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Film_info_window)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Film_info_window)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.review_pushButton = QtWidgets.QPushButton(Film_info_window)
        self.review_pushButton.setObjectName("review_pushButton")
        self.gridLayout.addWidget(self.review_pushButton, 9, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(Film_info_window)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.title_label = QtWidgets.QLabel(Film_info_window)
        self.title_label.setText("")
        self.title_label.setObjectName("title_label")
        self.gridLayout.addWidget(self.title_label, 0, 2, 1, 1)
        self.category_label = QtWidgets.QLabel(Film_info_window)
        self.category_label.setText("")
        self.category_label.setObjectName("category_label")
        self.gridLayout.addWidget(self.category_label, 1, 2, 1, 1)
        self.date_label = QtWidgets.QLabel(Film_info_window)
        self.date_label.setText("")
        self.date_label.setObjectName("date_label")
        self.gridLayout.addWidget(self.date_label, 2, 2, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(Film_info_window)
        self.textEdit.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 3, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(Film_info_window)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(Film_info_window)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 6, 2, 1, 1)
        self.close_pushButton = QtWidgets.QPushButton(Film_info_window)
        self.close_pushButton.setObjectName("close_pushButton")
        self.gridLayout.addWidget(self.close_pushButton, 9, 0, 1, 1)

        self.retranslateUi(Film_info_window)
        QtCore.QMetaObject.connectSlotsByName(Film_info_window)

    def retranslateUi(self, Film_info_window):
        _translate = QtCore.QCoreApplication.translate
        Film_info_window.setWindowTitle(_translate("Film_list", "KinoSearch"))
        self.label.setText(_translate("Film_info_window", "Название:"))
        self.label_4.setText(_translate("Film_info_window", "Краткое описание:"))
        self.goto_actors_pushButton.setText(_translate("Film_info_window", "Актеры"))
        self.label_2.setText(_translate("Film_info_window", "Жанр:"))
        self.label_5.setText(_translate("Film_info_window", "Год выпуска:"))
        self.label_3.setText(_translate("Film_info_window", "Время:"))
        self.review_pushButton.setText(_translate("Film_info_window", "Оставить отзыв"))
        self.label_6.setText(_translate("Film_info_window", "Режиссер:"))
        self.close_pushButton.setText(_translate("Film_info_window", "Закрыть"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Film_info_window = QtWidgets.QDialog()
    ui = Ui_Film_info_window()
    ui.setupUi(Film_info_window)
    Film_info_window.show()
    sys.exit(app.exec_())
