# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\user\PycharmProject\SMRPprjct\ui\from_designer\Film_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Film_list(object):
    def setupUi(self, Film_list):
        Film_list.setObjectName("Film_list")
        Film_list.resize(588, 328)
        self.gridLayout = QtWidgets.QGridLayout(Film_list)
        self.gridLayout.setObjectName("gridLayout")
        self.gosearch_pushButton = QtWidgets.QPushButton(Film_list)
        self.gosearch_pushButton.setObjectName("gosearch_pushButton")
        self.gridLayout.addWidget(self.gosearch_pushButton, 0, 5, 1, 1)
        self.backto_choose_pushButton = QtWidgets.QPushButton(Film_list)
        self.backto_choose_pushButton.setObjectName("backto_choose_pushButton")
        self.gridLayout.addWidget(self.backto_choose_pushButton, 2, 0, 1, 2)
        self.category_comboBox = QtWidgets.QComboBox(Film_list)
        self.category_comboBox.setObjectName("category_comboBox")
        self.gridLayout.addWidget(self.category_comboBox, 0, 4, 1, 1)
        self.Film_tableWidget = QtWidgets.QTableWidget(Film_list)
        self.Film_tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.Film_tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.Film_tableWidget.setObjectName("Film_tableWidget")
        self.Film_tableWidget.setColumnCount(5)
        self.Film_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Film_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Film_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Film_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Film_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Film_tableWidget.setHorizontalHeaderItem(4, item)
        self.gridLayout.addWidget(self.Film_tableWidget, 1, 0, 1, 6)
        self.label = QtWidgets.QLabel(Film_list)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.search_lineEdit = QtWidgets.QLineEdit(Film_list)
        self.search_lineEdit.setObjectName("search_lineEdit")
        self.gridLayout.addWidget(self.search_lineEdit, 0, 1, 1, 3)
        self.goto_Film_pushButton = QtWidgets.QPushButton(Film_list)
        self.goto_Film_pushButton.setObjectName("goto_Film_pushButton")
        self.gridLayout.addWidget(self.goto_Film_pushButton, 2, 4, 1, 2)
        self.change_table_pushButton = QtWidgets.QPushButton(Film_list)
        self.change_table_pushButton.setObjectName("change_table_pushButton")
        self.gridLayout.addWidget(self.change_table_pushButton, 2, 2, 1, 2)

        self.retranslateUi(Film_list)
        QtCore.QMetaObject.connectSlotsByName(Film_list)

    def retranslateUi(self, Film_list):
        _translate = QtCore.QCoreApplication.translate
        Film_list.setWindowTitle(_translate("Film_list", "Form"))
        self.gosearch_pushButton.setText(_translate("Film_list", "Найти"))
        self.backto_choose_pushButton.setText(_translate("Film_list", "Назад к выбору"))
        item = self.Film_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Film_list", "ID"))
        item = self.Film_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Film_list", "Название:"))
        item = self.Film_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Film_list", "Жанр:"))
        item = self.Film_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Film_list", "Время:"))
        item = self.Film_tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Film_list", "Год выпуска:"))
        self.label.setText(_translate("Film_list", "Поиск:"))
        self.goto_Film_pushButton.setText(_translate("Film_list", "Перейти на страницу фильма"))
        self.change_table_pushButton.setText(_translate("Film_list", "Редактор таблицы"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Film_list = QtWidgets.QWidget()
    ui = Ui_Film_list()
    ui.setupUi(Film_list)
    Film_list.show()
    sys.exit(app.exec_())
