# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Window_reg.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from DATAbase import User  # для дополнения в базу данных пользователей
from DATAbase import get_session
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
session = get_session()
#session.query(User).delete()  # отчистка всего
#session.commit()

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(374, 156)
        font = QtGui.QFont()
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("логотип_приложения.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        font.setPointSize(8)
        Form.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("MS Outlook")
        font.setPointSize(20)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 2)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 2, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 3, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 3, 3, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.new_user()
        self.pushButton.clicked.connect(Form.close)  # отмена
        self.pushButton_2.clicked.connect(self.new_user)  # Подтверждение регистрации
        self.pushButton_2.clicked.connect(Form.close)  # закрытие после регистрации

    def new_user(self):
        login = self.lineEdit.text()
        #print(login)
        password = self.lineEdit_2.text()
        user_check = session.query(User).filter(User.login == login).all()  # ищем юзера по нику
        if (len(user_check) != 0):
            error2 = QMessageBox()
            error2.setWindowTitle("Ошибка")
            error2.setText("Пользователь с таким ником уже существует")  # всплывающее окно
            error2.setIcon(QMessageBox.Warning)
            error2.setStandardButtons(QMessageBox.Ok)
            error2.exec_()
            print("Пользователь с таким ником уже существует")
        else:
            print(len(login))
            if(len(login) != 0):
                new_user = User(login = login, password = password)
                session.add(new_user)
                session.commit()
                session.close()
                exeption = QMessageBox()
                exeption.setWindowTitle("Подтверждение")
                exeption.setText("Регистрация успешно завершена!")  # всплывающее окно
                exeption.setIcon(QMessageBox.Information)
                exeption.setStandardButtons(QMessageBox.Ok)
                exeption.exec_()
                print("Пользователь успешно добавлен")


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "KinoSearch"))
        self.label.setText(_translate("Form", "Регистрация"))
        self.label_2.setText(_translate("Form", "Логин:"))
        self.label_3.setText(_translate("Form", "Пароль:"))
        self.pushButton.setText(_translate("Form", "Отмена"))
        self.pushButton_2.setText(_translate("Form", "Подтвердить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())