# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Menuu.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5.QtWidgets import QApplication

from windows import FilmList

import random
from DATAbase import Film,Admin
from DATAbase import get_session
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

session = get_session()
#session.query(User).delete()  # отчистка всего
#session.commit()

class Ui_Form_2(object):
    def __init__ (self,a):
        self.user_check = a

    def setupUi(self, Form_2):
        Form_2.setObjectName("Form_2")
        Form_2.resize(315, 308)
        Form_2.setStyleSheet("background-color: rgb(255, 241, 42);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("логотип_приложения.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form_2.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form_2)
        font = QtGui.QFont()
        font.setFamily("Showcard Gothic")
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.Films = QtWidgets.QPushButton(Form_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Films.setFont(font)
        self.Films.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.Films.setObjectName("Films")
        self.verticalLayout.addWidget(self.Films)
        self.Serials = QtWidgets.QPushButton(Form_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Serials.setFont(font)
        self.Serials.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.Serials.setObjectName("Serials")
        self.verticalLayout.addWidget(self.Serials)
        self.Game = QtWidgets.QPushButton(Form_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Game.setFont(font)
        self.Game.setStyleSheet("background-color: rgb(255, 170, 255);")
        self.Game.setObjectName("Game")
        self.verticalLayout.addWidget(self.Game)

        self.retranslateUi(Form_2)
        QtCore.QMetaObject.connectSlotsByName(Form_2)
        self.Films.clicked.connect(self.open_films)  # фильмы
        self.Serials.clicked.connect(self.open_serials)  # сериалы
        self.Game.clicked.connect(self.open_game)  # рандомный фильм



    #def Game(self):
    def open_films(self):
        if(self.user_check == 1):
            print("Таблица для Админа")
        self.new_window = FilmList()
        self.new_window.show()
        print("Фильмы")

    def open_serials(self):
        print("Сериалы")

    def open_game(self):
        # открытие окна с рандомным фильмом
        exeption = QMessageBox()
        exeption.setWindowTitle("Игра")
        a = random.randint( 75, 114)
        print(a)
        random_film = session.query(Film).filter(Film.film_id == a).all()  # ищем рандомный фильм
        print(random_film)

        exeption.setText(random_film[0].film_title)  # всплывающее окно
        exeption.setIcon(QMessageBox.Information)
        exeption.setStandardButtons(QMessageBox.Ok)
        exeption.exec_()
        print("рандомный фильм")

    def retranslateUi(self, Form_2):
        _translate = QtCore.QCoreApplication.translate
        Form_2.setWindowTitle(_translate("Form_2", "KinoSearch"))
        self.label.setText(_translate("Form_2", "KinoSearch"))
        self.Films.setText(_translate("Form_2", "Фильмы"))
        self.Serials.setText(_translate("Form_2", "Сериалы"))
        self.Game.setText(_translate("Form_2", "Случайный"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_2 = QtWidgets.QWidget()
    ui = Ui_Form_2()
    ui.setupUi(Form_2)
    Form_2.show()
    sys.exit(app.exec_())
